[workspace]
authors = ["xspoole <xspoole@gmail.com>"]
channels = ["conda-forge"]
name = "hw2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.3,<3"
scipy = ">=1.17.1,<2"
matplotlib = ">=3.10.9,<4"
ipykernel = ">=7.2.0,<8"
sympy = ">=1.14.0,<2"
