[workspace]
authors = ["xspoole <xspoole@gmail.com>"]
channels = ["conda-forge"]
name = "ph364"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
sep = ">=1.4.1,<2"
matplotlib = ">=3.10.9,<4"
numpy = ">=2.4.3,<3"
astropy = ">=7.2.0,<8"
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"
nbconvert = ">=7.17.1,<8"
scipy = ">=1.17.1,<2"
